### ISSUE TITLE
Trouble getting exit_code to work

### ISSUE THREAD

**Issue by spier** [peter-evans/link-checker#21]
Hi, and thanks for building this GitHub Action for link checking!

I configured the Action exactly as documented here:
https://github.com/marketplace/actions/link-checker#creating-a-failing-check-for-link-errors

```
on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *
    - name: Fail if there were link errors
       run: exit ${{ steps.lc.outputs.exit_code }}
```

When this Action is run, I get the following error message:

> Check failure on line 17 in .github/workflows/main.yml
> 
> GitHub Actions
> / .github/workflows/main.yml
> 
> Parse error
> You have an error in your yaml syntax on line 17

Line 17 is the last one in the example above i.e.
```run: exit ${{ steps.lc.outputs.exit_code }}```

Any idea what might be wrong here?

**Comment by peter-evans** [comment]
Hi @spier 

I made a small mistake on that line in the README. I've corrected it now.
Please try the following.

```
on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
```
