### ISSUE TITLE
Strange warning

### ISSUE THREAD

**Issue by karlbrown-va** [peter-evans/link-checker#24]
I get a strange warning as follows when running this as a github action:
```
##[warning]Unexpected input 'args', valid inputs are ['']`
Run peter-evans/link-checker@v1
```

Then the following under 'annotations'
```
 Check warning on line 1 in .github

@github-actions
github-actions
/ lint

.github#L1
Unexpected input 'args', valid inputs are ['']
```

File is as follows:
```
# Simple workflow for documentation checking
name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -r *

    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
```

Any idea what might be causing this?

**Comment by peter-evans** [comment]
Hi @karlbrown-va 

This is likely a workflow formatting issue, but I don't see anything obviously wrong with your workflow. 

Check the whitespace before `args` and make sure it's properly indented using spaces.
```
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -r *
```
