### ISSUE TITLE
Define the Liche Document Root

### ISSUE THREAD

**Issue by praneesha** [peter-evans/link-checker#32]
@peter-evans - I have configured the Link Checker as follows.

```
on: [push]
name: Link Checker Example Command
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -r learn swan-lake 1.1 1.0 -x 0.990 -d /ballerina-dev-website/ 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Link Checker Report
          path:  ./link-checker/out.md
```

However, the links that already available also get listed as `no such file or directory` as shown below.

<img width="768" alt="Screenshot 2020-10-28 at 14 59 14" src="https://user-images.githubusercontent.com/11707273/97417859-2aab6e00-192e-11eb-8443-7f45173e4b46.png">

How do I define the root directory `-d`correctly for absolute paths in the Liche arguments?

**Comment by peter-evans** [comment]
Hi @praneesha 

I think this might work:
```
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -r learn swan-lake 1.1 1.0 -x 0.990 -d ${{ github.workspace }}
```

**Comment by praneesha** [comment]
@peter-evans - Thanks for the help! Still the issue prevails now with the `Stat` URL being appended with an unnecessary `/home/runner/work/ballerina-dev-website/` part as shown below.

<img width="825" alt="Screenshot 2020-10-29 at 10 52 04" src="https://user-images.githubusercontent.com/11707273/97528988-fc349e00-19d4-11eb-9827-22528afd14d9.png">

**Comment by c-martinez** [comment]
Hi @peter-evans,

I ran into a similar issue and tried your proposed solution (using `-d ${{ github.workspace }}`), but was still not working. I tried this instead:

```yaml
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -r -d /github/workspace
```

I think when the docker run is started, it is doing something like `-v "${{ github.workspace }}":"/github/workspace"`, so the repo files end up in `/github/workspace` inside the docker image.
