### ISSUE TITLE
exclude doesn't appear to work

### ISSUE THREAD

**Issue by booyaa** [peter-evans/link-checker#36]
```yaml
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -r -x 'github|portal|windows' src/*
```

The exclusion regex `'github|portal|windows'` doesn't work. 

I've tested locally using liche v0.2.0 and the exclusions do work `liche -r -x 'github|portal|windows' src/*`
