### ISSUE TITLE
Use latest version of Liche

### ISSUE THREAD

**Issue by SvanBoxel** [peter-evans/link-checker#9]
A new version of Liche was released yesterday. Could we make sure we use the latest and greatest? 

https://github.com/raviqqe/liche/releases/tag/0.2.0

**Comment by peter-evans** [comment]
Thanks for letting me know. Updated!

Published a `v1` major version that you can follow. Or you can use `@v1.1.0` to pin the version.
```
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *
```
